name: Update Daily Orca

on:
  schedule:
    - cron: '0 0 * * *'  # Every day at midnight UTC
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Install jq
        run: sudo apt-get install -y jq

      - name: Get Today’s Date
        id: date
        run: echo "today=$(date +%Y-%m-%d)" >> $GITHUB_OUTPUT

      - name: Fetch Unsplash Image
        run: |
          set +e  # Don't exit on error — handle manually

          DATE="${{ steps.date.outputs.today }}"
          SEED=$(date +%d)
          if [ $((SEED % 2)) -eq 0 ]; then
            QUERY="orca"
          else
            QUERY="killer%20whale"
          fi

          echo "Using query: $QUERY"
          echo "Date seed: $DATE"

          RESPONSE=$(curl -s "https://api.unsplash.com/photos/random?query=$QUERY&client_id=$UNSPLASH_KEY&sig=$DATE")

          # Optional: show full API response for debugging
          echo "API response:"
          echo "$RESPONSE"

          # Print any Unsplash error messages
          echo "$RESPONSE" | jq -r '.errors[]?'

          IMAGE_URL=$(echo "$RESPONSE" | jq -r '.urls.full')

          if [ -z "$IMAGE_URL" ] || [ "$IMAGE_URL" = "null" ]; then
            echo "Failed to fetch image"
            echo '{"imageUrl": ""}' > daily-orca.json
          else
            echo "Fetched: $IMAGE_URL"
            echo "{\"imageUrl\": \"$IMAGE_URL\"}" > daily-orca.json
          fi

          exit 0  # Always succeed — don’t fail workflow on image issues
        env:
          UNSPLASH_KEY: ${{ secrets.UNSPLASH_KEY }}

      - name: Commit and Push
        uses: EndBug/add-and-commit@v9
        with:
          author_name: github-actions
          author_email: github-actions@github.com
          message: "Update image for ${{ steps.date.outputs.today }}"
