name: Update Daily Orca

on:
  schedule:
    - cron: '0 0 * * *'  # Every day at midnight UTC
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Install jq
        run: sudo apt-get install -y jq

      - name: Get Today’s Date
        id: date
        run: echo "today=$(date +%Y-%m-%d)" >> $GITHUB_OUTPUT

      - name: Fetch Unsplash Image
        run: |
          set +e  # Don't exit on errors

          DATE="${{ steps.date.outputs.today }}"
          SEED=$(date +%d)
          if [ $((SEED % 2)) -eq 0 ]; then
            QUERY="orca"
          else
            QUERY="killer%20whale"
          fi

          echo "Using query: $QUERY"
          echo "Date seed: $DATE"

          RESPONSE=$(curl -s "https://api.unsplash.com/photos/random?query=$QUERY&count=10&client_id=$UNSPLASH_KEY&sig=$DATE")

          echo "API response received"

          echo "$RESPONSE" | jq -r '.errors[]?'  # show error messages if any

          # Try to find the first image with 'orca' or 'whale' in its alt_description
          IMAGE_URL=$(echo "$RESPONSE" | jq -r '[.[] | select(.alt_description | test("orca|whale"; "i"))][0].urls.full')

          # If no match found, fallback to the first image anyway
          if [ -z "$IMAGE_URL" ] || [ "$IMAGE_URL" = "null" ]; then
            echo "No relevant match found, falling back to first result"
            IMAGE_URL=$(echo "$RESPONSE" | jq -r '.[0].urls.full')
          fi

          # Final check
          if [ -z "$IMAGE_URL" ] || [ "$IMAGE_URL" = "null" ]; then
            echo "Failed to fetch any valid image"
            echo '{"imageUrl": ""}' > daily-orca.json
          else
            echo "Fetched image: $IMAGE_URL"
            echo "{\"imageUrl\": \"$IMAGE_URL\"}" > daily-orca.json
          fi

          exit 0
        env:
          UNSPLASH_KEY: ${{ secrets.UNSPLASH_KEY }}

      - name: Commit and Push
        uses: EndBug/add-and-commit@v9
        with:
          author_name: github-actions
          author_email: github-actions@github.com
          message: "Update image for ${{ steps.date.outputs.today }}"
